# Heltec / Hiletgo ESP32 V3
# Although, board works for this project, it will not output log on serial port unless special cable adapter is added.
# Board will flash via USB-C to USB-C cable due to special conditions during boot, but after boot will not log to USB-C serial

# The Heltec V3 board has an omission in its Type-C port design. It lacks two standard CC (configuration channel) pulldown resistors.
# Use a USB-A to USB-C cable plugged into a standard USB-A port on your computer. This bypasses the smart handshake and forces the connection alive

substitutions:
  pin_ir_receiver: GPIO48   # IR sensor. 
  pin_indicator_LED: GPIO35 # LED indicator (both ESP32-C3 and C6)
  pin_action_btn: GPIO0     # use boot button for actions.
  wifi_tx_power: "15dB"
  
# Core Architecture Declaration
esp32:
  board: esp32-s3-devkitc-1 
  framework:
    type: esp-idf
  
# i2c Display Pins
i2c: 
  sda: GPIO17
  scl: GPIO18
  frequency: 400kHz
  scan: false # to prevent startup crashes during boot scans
  id: bus_a
  
# ============= END Configuration Options KUO ==========
  
globals:
    # ======= myDisplay display globals
  - id: myDisplay_line1
    type: std::string  
    restore_value: no
    initial_value: ''

  - id: myDisplay_line2
    restore_value: no
    type: std::string  
    initial_value: ''
    
  - id: myDisplay_line3
    restore_value: no
    type: std::string  
    initial_value: ''
    
switch:
  - platform: gpio # indicator LED that lights up when sniffing
    pin:
      number: ${pin_indicator_LED}
      inverted: false
    id: indicator_led
  
  - platform: gpio
    pin:
      number: GPIO36
      inverted: true   # Turns power ON when ESPHome sets state to "ON"
    id: vext_power
    restore_mode: ALWAYS_ON # Force the power rail alive immediately at boot
  
  
script:
  - id: flash_led_custom
    parameters:
      count: int         # Number of flashes
      dwell: int         # duration of flash in msec
      red: float         # Ignored on C3, kept for API matching
      green: float       # Ignored on C3, kept for API matching
      blue: float        # Ignored on C3, kept for API matching
    mode: queued
    then:
      - repeat:
          count: !lambda "return count;"
          then:
            # --- TURN BINARY LED ON ---
            - switch.turn_on: indicator_led
            - delay: !lambda "return dwell;"
  
            # --- TURN BINARY LED OFF ---
            - switch.turn_off: indicator_led
            - delay: !lambda "return dwell;"
               
  - id: turn_led_on_custom
    parameters:
      red: float         # Ignored on C3, kept for API matching
      green: float       # Ignored on C3, kept for API matching
      blue: float        # Ignored on C3, kept for API matching
      brightness: float  # Ignored on C3, kept for API matching
    mode: restart
    then:
      - switch.turn_on: indicator_led

  - id: turn_led_off_custom
    mode: restart
    then:
      - switch.turn_off: indicator_led

# ========  Display Specific Implementation ========

font:
  - file: "gfonts://JetBrains Mono"
    id: my_fontSmall
    size: 9

  - file: "gfonts://JetBrains Mono"
    id: my_fontMedium
    size: 10

  - file: "gfonts://JetBrains Mono"
    id: my_fontLarge
    size: 12

    
# Built-in 72x40 SSD1306 OLED screen
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    id: myDisplay
    reset_pin: GPIO21
    offset_x: 0
    offset_y: 0
    rotation: 0
    update_interval: 0.1s

    
    pages:
      - id: active_page_std
        lambda: |-
          it.print(0, 0,  id(my_fontMedium), id(myDisplay_line1).c_str());
          it.print(0, 13, id(my_fontLarge), id(myDisplay_line2).c_str());
          it.print(0, 26, id(my_fontLarge), id(myDisplay_line3).c_str());

      - id: active_page_small
        lambda: |-
          it.print(0, 0,  id(my_fontSmall), id(myDisplay_line1).c_str());
          it.print(0, 14, id(my_fontSmall), id(myDisplay_line2).c_str());
          it.print(0, 26, id(my_fontSmall), id(myDisplay_line3).c_str());

      - id: blank_page
        lambda: |-
          // Leaving lambda completely blank turns all pixels off safely
