# ============= BEGIN Configuration Options KUO ==========

substitutions:
# ***** basic board and GPIO wiring
  board_type: "esp32-s3-devkitc-1" # Map to valid framework target to accept ESP32-S3R8 core
  framework_type: "esp-idf" 
  
  pin_ir_receiver: GPIO2
  pin_indicator_LED: GPIO38
  pin_boot_btn: GPIO0 


# ===========================================================

# Core Architecture Declaration
esp32:
  board: ${board_type}
  variant: esp32s3              # Keeps compilation tuned for the S3 chip core
  framework:
    type: esp-idf
#  partitions: ir-common-kuo/appkit/partitions.csv


esphome:
  name: kuo-display-driver
  on_boot:
    priority: 200.0            # Executes immediately after the hardware components setup
    then:
      - light.turn_on:
          id: display_backlight
          brightness: 30%       # Instantly overrides full brightness spike
          
          
# Native Onboard LCD Backlight Dimming Driver Control
output:
  - platform: ledc
    id: backlight_pwm
    pin: GPIO46    
    frequency: 1000 Hz
          
light:
  - platform: esp32_rmt_led_strip
    id: sniffer_led
    pin: ${pin_indicator_LED}
    chipset: WS2812
    num_leds: 1
    rgb_order: RGB
    name: "Sniffer Indicator"

  - platform: monochromatic  
    name: "Display Backlight"
    id: display_backlight
    output: backlight_pwm
    default_transition_length: 0s
    restore_mode: ALWAYS_ON     # Forces display to turn on automatically at boot

script:
  - id: flash_led_custom
    parameters:
      count: int         # Number of flashes
      red: float         # Red value (0.0 to 1.0)
      green: float       # Green value (0.0 to 1.0)
      blue: float        # Blue value (0.0 to 1.0)
    mode: restart
    then:
      - repeat:
          count: !lambda "return count;"
          then:
            # --- TURN RGB LED ON WITH DYNAMIC COLOR ---
            - light.turn_on:
                id: sniffer_led
                red: !lambda "return red;"
                green: !lambda "return green;"
                blue: !lambda "return blue;"
                brightness: 0.2
                transition_length: 0s
            - delay: 150ms

            # --- TURN RGB LED OFF ---
            - light.turn_off:
                id: sniffer_led
                transition_length: 0s
            - delay: 150ms
            
  - id: turn_led_on_custom
    parameters:
      red: float         # Red channel (0.0 to 1.0)
      green: float       # Green channel (0.0 to 1.0)
      blue: float        # Blue channel (0.0 to 1.0)
      brightness: float  # Brightness (0.0 to 1.0)
    mode: restart
    then:
      - light.turn_on:
          id: sniffer_led
          red: !lambda "return red;"
          green: !lambda "return green;"
          blue: !lambda "return blue;"
          brightness: !lambda "return brightness;"
          transition_length: 0s  
          
  - id: turn_led_off_custom
    mode: restart
    then:
      - light.turn_off:
          id: sniffer_led
          transition_length: 0s  

# ========  Display Specific Implementation ========

font:
  - file: "gfonts://Roboto"
    id: my_fontSmall
    size: 25
  - file: "gfonts://Roboto"
    id: my_fontMedium
    size: 30
  - file: "gfonts://Roboto"
    id: my_fontLarge
    size: 40
    
spi:
  clk_pin: GPIO40
  mosi_pin: GPIO45


# Master Display Component Configuration
display:
  - platform: st7789v
    id: oled_display
    model: WAVESHARE_1.47IN_172X320  
    cs_pin: GPIO42
    dc_pin: GPIO41
    reset_pin: GPIO39
    rotation: 270                    
    update_interval: 0.3s

    on_page_change:
      - to: blank_page
        then:
          - light.turn_off: display_backlight
      - from: blank_page
        then:
          - light.turn_on:
              id: display_backlight
              brightness: 30%

    pages:
      - id: active_page_std
        lambda: |-
          it.print(5, 30,  id(my_fontMedium), id(OLED_line1).c_str());
          it.print(5, 60, id(my_fontLarge), id(OLED_line2).c_str());
          it.print(5, 100, id(my_fontLarge), id(OLED_line3).c_str());

      - id: active_page_small
        lambda: |-
          it.print(5, 30,  id(my_fontSmall), id(OLED_line1).c_str());
          it.print(5, 60, id(my_fontSmall), id(OLED_line2).c_str());
          it.print(5, 90, id(my_fontSmall), id(OLED_line3).c_str());

      - id: blank_page
        lambda: |-
          // Leaving lambda completely blank turns all pixels off safely
