# ============= BEGIN Configuration Options KUO ==========

substitutions:
  pin_ir_receiver: GPIO1
  pin_indicator_LED: GPIO8
  pin_action_btn: GPIO9 # use boot button to start actions

# Core Architecture Declaration

esp32:
  board: esp32-c6-devkitc-1
  partitions: ir-common-kuo/appkit/partitions.csv  #larger app partition needed 
  framework:
    type: esp-idf
# ============= END Configuration Options KUO ==========

esphome:
  on_boot:
    # 800.0f runs BEFORE the display (400.0f) initializes, giving us structural control
    - priority: 800.0
      then:
        - delay: 1.5s                      # Give physical power lines time to stabilize

    - priority: -100 # 4. Wait until the very end of the boot sequence when it is safe
      then:
        - light.turn_on:
            id: display_backlight
            brightness: 0.5
            
            
globals:
    # ======= myDisplay display globals
  - id: myDisplay_line1
    type: std::string  
    restore_value: no
    initial_value: ''

  - id: myDisplay_line2
    restore_value: no
    type: std::string  
    initial_value: ''
    
  - id: myDisplay_line3
    restore_value: no
    type: std::string  
    initial_value: ''
              
output:
  - platform: ledc
    pin: 
      number: GPIO22
      mode: OUTPUT        # Restores standard pushing power for the backlight circuit
    id: backlight_pwm
    frequency: 1000Hz     # Explicitly sets frequency for ESP-IDF stability
    min_power: 0.0
    max_power: 1.0
    
      
light:
  - platform: esp32_rmt_led_strip # neopixel
    id: indicator_led
    pin: ${pin_indicator_LED}
    chipset: WS2812
    num_leds: 1
    rgb_order: RGB
    name: "Sniffer Indicator"
    internal: true

  - platform: monochromatic  
    name: "Display Backlight"
    id: display_backlight
    output: backlight_pwm
    default_transition_length: 0s
    gamma_correct: 0          # Keeps response linear 
    restore_mode: ALWAYS_OFF    
    internal: true

script:
  - id: flash_led_custom
    parameters:
      count: int         # Number of flashes
      dwell: int         # duration of flash in msec
      red: float         # Red value (0.0 to 1.0)
      green: float       # Green value (0.0 to 1.0)
      blue: float        # Blue value (0.0 to 1.0)
    mode: queued
    then:
      - repeat:
          count: !lambda "return count;"
          then:
            # --- TURN RGB LED ON WITH DYNAMIC COLOR ---
            - light.turn_on:
                id: indicator_led
                red: !lambda "return red;"
                green: !lambda "return green;"
                blue: !lambda "return blue;"
                brightness: 0.2
                transition_length: 0s
            - delay: !lambda "return dwell;"

            # --- TURN RGB LED OFF ---
            - light.turn_off:
                id: indicator_led
                transition_length: 0s
            - delay: !lambda "return dwell;"
            
  - id: turn_led_on_custom
    parameters:
      red: float         # Red channel (0.0 to 1.0)
      green: float       # Green channel (0.0 to 1.0)
      blue: float        # Blue channel (0.0 to 1.0)
      brightness: float  # Brightness (0.0 to 1.0)
    mode: restart
    then:
      - light.turn_on:
          id: indicator_led
          red: !lambda "return red;"
          green: !lambda "return green;"
          blue: !lambda "return blue;"
          brightness: !lambda "return brightness;"
          transition_length: 0s  
          
  - id: turn_led_off_custom
    mode: restart
    then:
      - light.turn_off:
          id: indicator_led
          transition_length: 0s  


# ========  Display Specific Implementation ========

font:
  - file: "gfonts://Roboto"
    id: my_fontSmall
    size: 30
  - file: "gfonts://Roboto"
    id: my_fontMedium
    size: 35
  - file: "gfonts://Roboto"
    id: my_fontLarge
    size: 40

    
spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

# Master Display Component Configuration
display:
  - platform: mipi_spi
    id: myDisplay
    model: st7789v
    dimensions:
      width: 172
      height: 320
      offset_width: 34
      offset_height: 0
      pad_width: 34
      pad_height: 0
    rotation: 270
    invert_colors: true
    cs_pin: GPIO14
    dc_pin: GPIO15
    # Use the hardware trace as an enable trigger to force a startup delay:
    enable_pin: 
      number: GPIO21
    update_interval: 0.1s

    data_rate: 40MHz # Add this to push pixels faster    

   
    on_page_change:
      - then:
          - if:
              condition:
                lambda: 'return to == id(blank_page);'
              then:
                - light.turn_off:
                    id: display_backlight

              else:
                - light.turn_on:
                    id: display_backlight
                    brightness: 100%




    pages:
      - id: active_page_std
        lambda: |-
            auto L1color = Color(255, 100, 0);
            auto L2color = Color(255, 120, 0);
            auto L3color = Color(255, 150, 0);

            it.print(5, 30,  id(my_fontSmall), L1color, id(myDisplay_line1).c_str());
            it.print(5, 75,  id(my_fontSmall), L2color, id(myDisplay_line2).c_str());
            it.print(5, 115, id(my_fontLarge), L3color,  id(myDisplay_line3).c_str());

      - id: active_page_small
        lambda: |-
            auto L1color = Color(255, 130, 0);
            auto L2color = Color(255, 130, 0);
            auto L3color = Color(255, 130, 0);
            
            it.print(5, 30,  id(my_fontMedium), L1color, id(myDisplay_line1).c_str());
            it.print(5, 70,  id(my_fontMedium), L2color, id(myDisplay_line2).c_str());
            it.print(5, 110,  id(my_fontMedium),L3color, id(myDisplay_line3).c_str());

      - id: blank_page
        lambda: |-
          // Leaving lambda completely blank turns all pixels off safely

