# ============= BEGIN Configuration Options KUO ==========

substitutions:

  pin_ir_receiver: GPIO1   # IR sensor. 
  pin_indicator_LED: GPIO8 # LED indicator (both ESP32-C3 and C6)
  pin_sniff_btn: GPIO9     # usually use boot button for sniff. ESP32-c3 and ESP32-C6 use pin 9 for boot button. 


# Core Architecture Declaration
esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# i2c pins for # ESP32-C6-wroom-1 and dummy or optional i2c display. See also display later file
i2c: 
  sda: GPIO5 # suggested same as c3 with built in OLED
  scl: GPIO6 # suggested same as c3 with built in OLED
  frequency: 400kHz
  scan: false #to prevent startup crashes during boot scans
  id: bus_a
      
# ============= END Configuration Options KUO ==========

  
light:
  - platform: esp32_rmt_led_strip # neopixel
    id: sniffer_led
    pin: ${pin_indicator_LED}
    chipset: WS2812
    num_leds: 1
    rgb_order: GRB
    name: "Sniffer Indicator"
    
script:
  - id: flash_led_custom
    parameters:
      count: int         # Number of flashes
      red: float         # Red value (0.0 to 1.0)
      green: float       # Green value (0.0 to 1.0)
      blue: float        # Blue value (0.0 to 1.0)
    mode: restart
    then:
      - repeat:
          count: !lambda "return count;"
          then:
            # --- TURN RGB LED ON WITH DYNAMIC COLOR ---
            # Pass your script parameters to the light.turn_on action via lambdas
            - light.turn_on:
                id: sniffer_led
                red: !lambda "return red;"
                green: !lambda "return green;"
                blue: !lambda "return blue;"
                brightness: 0.2
                transition_length: 0s
            - delay: 150ms

            # --- TURN RGB LED OFF ---
            - light.turn_off:
                id: sniffer_led
                transition_length: 0s
            - delay: 150ms
            
            
  - id: turn_led_on_custom
    parameters:
      red: float         # Red channel (0.0 to 1.0)
      green: float       # Green channel (0.0 to 1.0)
      blue: float        # Blue channel (0.0 to 1.0)
      brightness: float  # Brightness (0.0 to 1.0)
    mode: restart
    then:
      - light.turn_on:
          id: sniffer_led
          red: !lambda "return red;"
          green: !lambda "return green;"
          blue: !lambda "return blue;"
          brightness: !lambda "return brightness;"
          transition_length: 0s  # Turns on instantly without a fade
          
          
  - id: turn_led_off_custom
    mode: restart
    then:
      - light.turn_off:
          id: sniffer_led
          transition_length: 0s  # Turns off instantly without a fade


# ========  Display Specific Implementation ========

font:
  - file: "gfonts://Roboto"
    id: my_fontSmall
    size: 9
    
  - file: "gfonts://Roboto"
    id: my_fontMedium
    size: 10

  - file: "gfonts://Roboto"
    id: my_fontLarge
    size: 11

    
# Built-in 72x40 SSD1306 OLED screen
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    id: myDisplay
    update_interval: 0.3s
    offset_x: 0
    offset_y: 0
    rotation: 0
    pages:
      - id: active_page_std
        lambda: |-
          it.print(0, 0,  id(my_fontMedium), id(myDisplay_line1).c_str());
          it.print(0, 9, id(my_fontLarge), id(myDisplay_line2).c_str());
          it.print(0, 20, id(my_fontLarge), id(myDisplay_line3).c_str());

      - id: active_page_small
        lambda: |-
          it.print(0, 0,  id(my_fontSmall), id(myDisplay_line1).c_str());
          it.print(0, 10, id(my_fontSmall), id(myDisplay_line2).c_str());
          it.print(0, 20, id(my_fontSmall), id(myDisplay_line3).c_str());

      - id: blank_page
        lambda: |-
          // Leaving lambda completely blank turns all pixels off safely
